version: '3'
services:

  #PHP Service
  php:
    build: ./php
    container_name: php
    working_dir: /var/www
    volumes:
      - ./src:/var/www:cached
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      - db  
      
  #Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php    
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0.29
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app-network
            
#Docker Networks
networks:
  app-network:
    driver: bridge
